spring.application.name=Desafio-Elite-Dev

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1


#cal.com
cal_live_a0da26267b8daadba65576e3752eac9e

#verzelId
3726710